# Generic synthesizable RTL, relative to this directory.
pkg/synth_pkg.sv
pkg/synth_register_pkg.sv
generated/synth_dsp_lut_pkg.sv
control/voice_bram_1r1w.sv
control/control_word_fifo.sv
control/control_action_fifo.sv
control/control_action_parser.sv
control/control_action_executor.sv
control/transactional_control_plane.sv
control/synth_control_plane.sv
memory/wave_memory_subsystem.sv
memory/voice_line_cache.sv
dsp/linear_interpolator.sv
dsp/gain_saturate.sv
dsp/voice_dsp_pipeline.sv
audio/stereo_chorus.sv
audio/fdn_reverb.sv
audio/effect_return_mixer.sv
audio/global_effects_chain.sv
audio/global_audio_effects_chain.sv
audio/lookahead_compressor.sv
audio/output_sample_fifo.sv
audio/render_credit_scheduler.sv
voice/voice_phase_frame.sv
voice/voice_endpoint_fetch.sv
voice/multi_voice_pipeline.sv
top/wavetable_render_core.sv
top/wavetable_cached_render_core.sv
