module tb_wavetable_render_core_asset;
  import synth_pkg::*;

  // Generated by tools/sf2_extract.py. It supplies memory depth, loop points,
  // phase increment, and output paths for this render run.
`include "render_config.svh"

`ifndef RENDER_BASE_ADDR_R
`define RENDER_BASE_ADDR_R RENDER_BASE_ADDR
`endif
`ifndef RENDER_LENGTH_R
`define RENDER_LENGTH_R RENDER_LENGTH
`endif
`ifndef RENDER_LOOP_START_R
`define RENDER_LOOP_START_R RENDER_LOOP_START
`endif
`ifndef RENDER_LOOP_END_R
`define RENDER_LOOP_END_R RENDER_LOOP_END
`endif

  // Unlike tb_wavetable_render_core, this testbench is not a strict unit test. It is a
  // render harness: drive the RTL for N samples and dump its exact PCM output.
  logic clk = 1'b0;
  logic rst;
  logic bus_valid;
  logic bus_write;
  logic [15:0] bus_address;
  logic [31:0] bus_wdata;
  logic [31:0] bus_rdata;
  logic bus_ready;
  logic bus_error;
  logic cmd_stream_valid;
  logic [31:0] cmd_stream_data;
  logic cmd_stream_ready;
  logic sample_tick;
  logic sample_valid;
  pcm_t sample_l;
  pcm_t sample_r;
  logic busy;
  mix_t mix_l;
  mix_t mix_r;
  global_audio_config_t audio_config;
  logic [1:0] effect_clear;
  wave_word_req_t mem_req;
  logic mem_req_ready;
  wave_word_rsp_t mem_rsp;
  logic ext_req_valid;
  logic ext_req_ready;
  logic [31:0] ext_req_addr;
  logic ext_rsp_valid;
  localparam int LINE_WORDS = 32;
  logic [LINE_WORDS*16-1:0] ext_rsp_data;
  cache_diagnostics_t cache_diagnostics;
  voice_pipeline_diagnostics_t voice_diagnostics;
  logic unused_status;
  int pcm_fd;
  int produced;

/* verilator lint_off BLKSEQ */
  always #5 clk <= ~clk;
/* verilator lint_on BLKSEQ */

  // Keep Verilator from warning about observed-but-unused status outputs. The
  // render harness does not need to inspect read data or busy status.
  assign unused_status = |bus_rdata | busy | (|cache_diagnostics) |
                         (|voice_diagnostics);

  wavetable_render_core dut (.*);

  voice_line_cache #(.LINE_WORDS(LINE_WORDS), .LINES_PER_VOICE(2)) memory_subsystem (
    .clk,
    .rst,
    .req(mem_req),
    .req_ready(mem_req_ready),
    .rsp(mem_rsp),
    .ext_req_valid,
    .ext_req_ready,
    .ext_req_addr,
    .ext_rsp_valid,
    .ext_rsp_data,
    .diagnostics_o(cache_diagnostics)
  );

  line_memory_model #(.DEPTH(RENDER_MEMORY_DEPTH), .LINE_WORDS(LINE_WORDS), .LATENCY(4)) memory_model (
    .clk,
    .rst,
    .req_valid(ext_req_valid),
    .req_ready(ext_req_ready),
    .req_addr(ext_req_addr),
    .rsp_valid(ext_rsp_valid),
    .rsp_data(ext_rsp_data)
  );

  function automatic logic [31:0] header(
    input command_opcode_t opcode,
    input logic [7:0] payload_words
  );
    header = {opcode, 8'd0, 8'd1, payload_words};
  endfunction

  task automatic push_word(input logic [31:0] data);
    @(negedge clk);
    while (!cmd_stream_ready) @(negedge clk);
    cmd_stream_data = data;
    cmd_stream_valid = 1'b1;
    @(negedge clk);
    cmd_stream_valid = 1'b0;
  endtask

  task automatic define_voice;
    if (RENDER_STEREO != 0) begin
      push_word(header(VOICE_DEFINE_STEREO, 8'd15));
      push_word(RENDER_BASE_ADDR);
      push_word(`RENDER_BASE_ADDR_R);
      push_word(RENDER_LENGTH);
      push_word(`RENDER_LENGTH_R);
      push_word(RENDER_LOOP_START);
      push_word(`RENDER_LOOP_START_R);
      push_word(RENDER_LOOP_END);
      push_word(`RENDER_LOOP_END_R);
      push_word(32'd0);
      push_word({30'd0, LOOP_MODE_NONE});
      push_word(32'h0000_4000);
      push_word(32'd0);
      push_word(32'd0);
      push_word(32'd0);
      push_word(32'd0);
    end else begin
      push_word(header(VOICE_DEFINE_MONO, 8'd11));
      push_word(RENDER_BASE_ADDR);
      push_word(RENDER_LENGTH);
      push_word(RENDER_LOOP_START);
      push_word(RENDER_LOOP_END);
      push_word(32'd0);
      push_word({30'd0, LOOP_MODE_NONE});
      push_word(32'h0000_4000);
      push_word(32'd0);
      push_word(32'd0);
      push_word(32'd0);
      push_word(32'd0);
    end
  endtask

  task automatic start_voice;
    push_word(header(VOICE_START, 8'd8));
    push_word({16'(`RENDER_GAIN_R), 16'(`RENDER_GAIN_L)});
    push_word(RENDER_PHASE_INC);
    push_word(32'd0);
    push_word(32'd0);
    push_word(32'd0);
    push_word(32'd0);
    push_word(32'd0);
    push_word(32'h0100_0000);
  endtask

  task automatic write_pcm16(input pcm_t sample);
    logic [15:0] word;
    begin
      // WAV/PCM stores little-endian signed 16-bit words. SystemVerilog fwrite
      // with %c emits one byte at a time.
      word = sample;
      $fwrite(pcm_fd, "%c%c", word[7:0], word[15:8]);
    end
  endtask

  task automatic request_sample;
    int timeout;
    begin
      // One sample_tick corresponds to one output frame in the generated WAV.
      // The hardware latency is variable with mono/stereo, so wait for valid.
      @(negedge clk);
      sample_tick = 1'b1;
      @(negedge clk);
      sample_tick = 1'b0;
      timeout = 0;
      while (!sample_valid && timeout < 1000) begin
        @(negedge clk);
        timeout++;
      end
      if (!sample_valid)
        $fatal(1, "sample response timed out at output sample %0d", produced);
      write_pcm16(sample_l);
      write_pcm16(sample_r);
      produced++;
    end
  endtask

  initial begin
    rst = 1'b1;
    bus_valid = 1'b0;
    bus_write = 1'b0;
    bus_address = '0;
    bus_wdata = '0;
    cmd_stream_valid = 1'b0;
    cmd_stream_data = 32'd0;
    sample_tick = 1'b0;
    produced = 0;

    // Load the SF2-derived wave memory and open the raw stereo PCM stream. The
    // Python post-process wraps this byte stream in a WAV container.
    $readmemh(RENDER_MEMH, memory_model.memory);
    pcm_fd = $fopen(RENDER_PCM, "wb");
    if (pcm_fd == 0)
      $fatal(1, "failed to open %s", RENDER_PCM);

    repeat (3) @(negedge clk);
    rst = 1'b0;

    define_voice();
    start_voice();
    repeat (40) @(negedge clk);

    // The output file is always stereo: mono instruments have already been
    // duplicated by the RTL into sample_l/sample_r.
    while (produced < RENDER_SAMPLE_COUNT)
      request_sample();

    $fclose(pcm_fd);
    $display("PASS: rendered %0d stereo samples to %s", produced, RENDER_PCM);
    $finish;
  end
endmodule
