#!/usr/bin/env python3
import math
from pathlib import Path


CB_STEP = 4
CB_MAX = 960
Q15_FULL = 32767
SV_OUT = Path("rtl/generated/synth_envelope_lut_pkg.sv")
CPP_OUT = Path("sim/harness/generated/envelope_lut.h")


def cb_to_q15(cb):
    if cb >= CB_MAX:
        return 0
    return int(round(Q15_FULL * math.pow(10.0, -float(cb) / 200.0)))


def values():
    return [cb_to_q15(cb) for cb in range(0, CB_MAX + 1, CB_STEP)]


def render_sv(vals):
    lines = [
        "// Generated by tools/gen_envelope_lut.py.",
        "// Do not edit by hand.",
        "/* verilator lint_off UNUSEDPARAM */",
        "package synth_envelope_lut_pkg;",
        f"  localparam int ENV_CB_LUT_STEP_CB = {CB_STEP};",
        f"  localparam int ENV_CB_LUT_LAST_INDEX = {len(vals) - 1};",
        f"  localparam logic [31:0] ENV_CB_SILENCE_Q8_8 = 32'd{CB_MAX << 8};",
        "  localparam logic signed [15:0] CB_TO_Q15_LUT [0:ENV_CB_LUT_LAST_INDEX] = '{",
    ]
    for idx in range(0, len(vals), 8):
        chunk = vals[idx:idx + 8]
        suffix = "," if idx + 8 < len(vals) else ""
        lines.append("    " + ", ".join(f"16'sd{value}" for value in chunk) + suffix)
    lines.extend([
        "  };",
        "endpackage",
        "/* verilator lint_on UNUSEDPARAM */",
        "",
    ])
    return "\n".join(lines)


def render_cpp(vals):
    lines = [
        "// Generated by tools/gen_envelope_lut.py.",
        "// Do not edit by hand.",
        "#pragma once",
        "",
        "#include <array>",
        "#include <cstdint>",
        "",
        "namespace render::envelope_lut {",
        f"constexpr uint32_t kCbStep = {CB_STEP}u;",
        f"constexpr uint32_t kCbSilenceQ8_8 = {CB_MAX}u << 8;",
        f"constexpr std::array<int16_t, {len(vals)}> kCbToQ15 = {{",
    ]
    for idx in range(0, len(vals), 12):
        chunk = vals[idx:idx + 12]
        suffix = "," if idx + 12 < len(vals) else ""
        lines.append("    " + ", ".join(str(value) for value in chunk) + suffix)
    lines.extend([
        "};",
        "}  // namespace render::envelope_lut",
        "",
    ])
    return "\n".join(lines)


def main():
    vals = values()
    SV_OUT.parent.mkdir(parents=True, exist_ok=True)
    CPP_OUT.parent.mkdir(parents=True, exist_ok=True)
    SV_OUT.write_text(render_sv(vals), encoding="utf-8")
    CPP_OUT.write_text(render_cpp(vals), encoding="utf-8")


if __name__ == "__main__":
    main()
