#!/usr/bin/env python3
import argparse
import math
from pathlib import Path


CB_MAX = 1000
Q15_FULL = 32767
CB_Q20_SCALE = 1 << 20
CB_TO_Q15_GUARD_BITS = 8
CB_TO_Q15_RESIDUAL_STEP_Q20 = 1 << 19
CB_TO_Q15_RESIDUAL_LAST_INDEX = 120
CB_TO_Q15_MAX_INTEGER_ERROR = 100
Q15_TO_CB_MANTISSA_BITS = 6
Q15_TO_CB_MANTISSA_SIZE = 1 << Q15_TO_CB_MANTISSA_BITS
Q15_TO_CB_MAX_ERROR_CB = 0.68
SV_OUT = Path("rtl/generated/synth_envelope_lut_pkg.sv")
CPP_OUT = Path("sim/harness/generated/envelope_lut.h")


def octave_q20():
    return int(round(200.0 * math.log10(2.0) * CB_Q20_SCALE))


def octave_lut():
    octave = octave_q20()
    return [index * octave for index in range(17)]


def cb_to_q15_mantissa():
    scale = Q15_FULL << CB_TO_Q15_GUARD_BITS
    return [
        int(round(scale * math.pow(10.0, -(index * 0.5) / 200.0)))
        for index in range(CB_TO_Q15_RESIDUAL_LAST_INDEX + 1)
    ]


def approximate_cb_to_q15(cb_q20, octaves, mantissa):
    if cb_q20 >= CB_MAX * CB_Q20_SCALE:
        return 0
    exponent = max(index for index, threshold in enumerate(octaves)
                   if threshold <= cb_q20)
    residual = cb_q20 - octaves[exponent]
    index = min(
        CB_TO_Q15_RESIDUAL_LAST_INDEX,
        (residual + CB_TO_Q15_RESIDUAL_STEP_Q20 // 2)
        // CB_TO_Q15_RESIDUAL_STEP_Q20,
    )
    scaled = mantissa[index] >> exponent
    return (scaled + (1 << (CB_TO_Q15_GUARD_BITS - 1))) >> CB_TO_Q15_GUARD_BITS


def validate_cb_to_q15(octaves, mantissa):
    max_integer_error = 0
    previous = Q15_FULL
    for cb_q8 in range(CB_MAX * 256 + 1):
        cb = cb_q8 / 256.0
        exact = 0 if cb >= CB_MAX else int(round(
            Q15_FULL * math.pow(10.0, -cb / 200.0)
        ))
        approx = approximate_cb_to_q15(cb_q8 << 12, octaves, mantissa)
        if approx > previous:
            raise RuntimeError("centibel-to-Q15 approximation is not monotonic")
        previous = approx
        max_integer_error = max(max_integer_error, abs(approx - exact))

    if max_integer_error > CB_TO_Q15_MAX_INTEGER_ERROR:
        raise RuntimeError(
            f"centibel-to-Q15 maximum integer error {max_integer_error} exceeds "
            f"{CB_TO_Q15_MAX_INTEGER_ERROR}"
        )
    return max_integer_error


def exact_q15_to_cb_q20(level):
    return int(round(-200.0 * math.log10(level / Q15_FULL) * CB_Q20_SCALE))


def q15_to_cb_tables():
    octave = octave_q20()
    residuals = [[] for _ in range(Q15_TO_CB_MANTISSA_SIZE)]

    for level in range(1, Q15_FULL):
        leading_zeros = 14 - (level.bit_length() - 1)
        normalized = level << leading_zeros
        index = (normalized >> (14 - Q15_TO_CB_MANTISSA_BITS)) & (
            Q15_TO_CB_MANTISSA_SIZE - 1
        )
        residuals[index].append(
            exact_q15_to_cb_q20(level) - leading_zeros * octave
        )

    mantissa = []
    for bucket in residuals:
        if not bucket:
            raise RuntimeError("empty Q15-to-centibel mantissa bucket")
        mantissa.append((min(bucket) + max(bucket) + 1) // 2)

    return mantissa


def validate_q15_to_cb(octave_lut, mantissa):
    max_error_q20 = 0
    total_error_q20 = 0
    for level in range(1, Q15_FULL):
        leading_zeros = 14 - (level.bit_length() - 1)
        normalized = level << leading_zeros
        index = (normalized >> (14 - Q15_TO_CB_MANTISSA_BITS)) & (
            Q15_TO_CB_MANTISSA_SIZE - 1
        )
        approx = octave_lut[leading_zeros] + mantissa[index]
        error = abs(approx - exact_q15_to_cb_q20(level))
        max_error_q20 = max(max_error_q20, error)
        total_error_q20 += error

    max_error_cb = max_error_q20 / CB_Q20_SCALE
    if max_error_cb > Q15_TO_CB_MAX_ERROR_CB:
        raise RuntimeError(
            f"Q15-to-centibel maximum error {max_error_cb:.6f} cB exceeds "
            f"{Q15_TO_CB_MAX_ERROR_CB:.6f} cB"
        )
    return max_error_cb, total_error_q20 / ((Q15_FULL - 1) * CB_Q20_SCALE)


def append_sv_array(lines, declaration, vals, columns, width=32):
    lines.append(declaration)
    for idx in range(0, len(vals), columns):
        chunk = vals[idx:idx + columns]
        suffix = "," if idx + columns < len(vals) else ""
        lines.append(
            "    " + ", ".join(f"{width}'d{value}" for value in chunk) + suffix
        )
    lines.append("  };")


def render_sv(octaves, cb_mantissa, q15_mantissa, max_integer_error,
              max_error_cb, mean_error_cb):
    lines = [
        "// Generated by tools/gen_envelope_lut.py.",
        "// Do not edit by hand.",
        f"// Centibel-to-Q15 max integer error: {max_integer_error}.",
        f"// Q15-to-centibel max/mean error: {max_error_cb:.6f}/{mean_error_cb:.6f} cB.",
        "/* verilator lint_off UNUSEDPARAM */",
        "package synth_envelope_lut_pkg;",
        f"  localparam logic [31:0] ENV_CB_SILENCE_Q12_20 = 32'd{CB_MAX << 20};",
    ]
    lines.append(f"  localparam int CB_TO_Q15_GUARD_BITS = {CB_TO_Q15_GUARD_BITS};")
    lines.append("  localparam int CB_TO_Q15_RESIDUAL_INDEX_SHIFT = 19;")
    append_sv_array(
        lines,
        f"  localparam logic [31:0] CB_OCTAVE_Q12_20_LUT [0:{len(octaves) - 1}] = '{{",
        octaves,
        4,
    )
    append_sv_array(
        lines,
        f"  localparam logic [23:0] CB_TO_Q15_MANTISSA_LUT [0:{len(cb_mantissa) - 1}] = '{{",
        cb_mantissa,
        4,
        24,
    )
    lines.append(f"  localparam int Q15_TO_CB_MANTISSA_BITS = {Q15_TO_CB_MANTISSA_BITS};")
    append_sv_array(
        lines,
        f"  localparam logic [31:0] Q15_TO_CB_MANTISSA_LUT [0:{len(q15_mantissa) - 1}] = '{{",
        q15_mantissa,
        4,
    )
    lines.extend([
        "endpackage",
        "/* verilator lint_on UNUSEDPARAM */",
        "",
    ])
    return "\n".join(lines)


def append_cpp_array(lines, declaration, vals, columns):
    lines.append(declaration)
    for idx in range(0, len(vals), columns):
        chunk = vals[idx:idx + columns]
        suffix = "," if idx + columns < len(vals) else ""
        lines.append("    " + ", ".join(f"{value}u" for value in chunk) + suffix)
    lines.append("};")


def render_cpp(octaves, cb_mantissa, q15_mantissa, max_integer_error,
               max_error_cb, mean_error_cb):
    lines = [
        "// Generated by tools/gen_envelope_lut.py.",
        "// Do not edit by hand.",
        f"// Centibel-to-Q15 max integer error: {max_integer_error}.",
        f"// Q15-to-centibel max/mean error: {max_error_cb:.6f}/{mean_error_cb:.6f} cB.",
        "#pragma once",
        "",
        "#include <array>",
        "#include <cstdint>",
        "",
        "namespace render::envelope_lut {",
        f"constexpr uint32_t kCbSilenceQ12_20 = {CB_MAX}u << 20;",
    ]
    lines.append(f"constexpr uint32_t kCbToQ15GuardBits = {CB_TO_Q15_GUARD_BITS}u;")
    lines.append("constexpr uint32_t kCbToQ15ResidualIndexShift = 19u;")
    append_cpp_array(
        lines,
        f"constexpr std::array<uint32_t, {len(octaves)}> kCbOctaveQ12_20 = {{",
        octaves,
        4,
    )
    append_cpp_array(
        lines,
        f"constexpr std::array<uint32_t, {len(cb_mantissa)}> kCbToQ15Mantissa = {{",
        cb_mantissa,
        4,
    )
    lines.append(f"constexpr uint32_t kQ15ToCbMantissaBits = {Q15_TO_CB_MANTISSA_BITS}u;")
    append_cpp_array(
        lines,
        f"constexpr std::array<uint32_t, {len(q15_mantissa)}> kQ15ToCbMantissa = {{",
        q15_mantissa,
        4,
    )
    lines.extend([
        "}  // namespace render::envelope_lut",
        "",
    ])
    return "\n".join(lines)


def generated_outputs():
    octaves = octave_lut()
    cb_mantissa = cb_to_q15_mantissa()
    q15_mantissa = q15_to_cb_tables()
    max_integer_error = validate_cb_to_q15(octaves, cb_mantissa)
    max_error_cb, mean_error_cb = validate_q15_to_cb(octaves, q15_mantissa)
    return {
        SV_OUT: render_sv(
            octaves,
            cb_mantissa,
            q15_mantissa,
            max_integer_error,
            max_error_cb,
            mean_error_cb,
        ),
        CPP_OUT: render_cpp(
            octaves,
            cb_mantissa,
            q15_mantissa,
            max_integer_error,
            max_error_cb,
            mean_error_cb,
        ),
    }


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify that generated outputs are current without rewriting them",
    )
    args = parser.parse_args()

    outputs = generated_outputs()
    if args.check:
        stale = [
            path for path, expected in outputs.items()
            if not path.exists() or path.read_text(encoding="utf-8") != expected
        ]
        if stale:
            paths = ", ".join(str(path) for path in stale)
            raise SystemExit(f"stale generated envelope LUT output: {paths}")
        return

    SV_OUT.parent.mkdir(parents=True, exist_ok=True)
    CPP_OUT.parent.mkdir(parents=True, exist_ok=True)
    for path, contents in outputs.items():
        path.write_text(contents, encoding="utf-8")


if __name__ == "__main__":
    main()
