module board_loader_render_tops #(
  parameter int LBA_WIDTH = 32,
  parameter int MIG_ADDR_WIDTH = 28,
  parameter int MIG_DATA_WIDTH = 128,
  parameter int LINE_WORDS = 8
) (
  input  logic                      clk,
  input  logic                      rst,

  input  logic                      loader_start,
  input  logic                      loader_ddr_init_calib_complete,
  output logic                      loader_busy,
  output logic                      loader_asset_loaded,
  output logic                      loader_sd_initialized,
  output logic [3:0]                loader_status_state,
  output logic [7:0]                loader_sd_error_code,
  output logic [7:0]                loader_error_code,
  output logic [31:0]               loader_bytes_loaded,
  output logic [31:0]               loader_sf2_size_bytes,
  output logic [LBA_WIDTH-1:0]      loader_current_lba,

  output logic                      sd_cmd_valid,
  input  logic                      sd_cmd_ready,
  output logic [5:0]                sd_cmd_index,
  output logic [31:0]               sd_cmd_arg,
  output logic [1:0]                sd_cmd_resp_type,
  output logic                      sd_cmd_data_read,
  output logic [15:0]               sd_cmd_block_len,
  output logic [15:0]               sd_cmd_block_count,
  input  logic                      sd_rsp_valid,
  input  logic [2:0]                sd_rsp_status,
  input  logic [119:0]              sd_rsp_data,
  input  logic                      sd_data_valid,
  output logic                      sd_data_ready,
  input  logic [7:0]                sd_data,
  input  logic                      sd_data_last,
  input  logic [2:0]                sd_data_status,

  output logic [MIG_ADDR_WIDTH-1:0] mig_app_addr,
  output logic [2:0]                mig_app_cmd,
  output logic                      mig_app_en,
  input  logic                      mig_app_rdy,
  output logic [MIG_DATA_WIDTH-1:0] mig_app_wdf_data,
  output logic [MIG_DATA_WIDTH/8-1:0] mig_app_wdf_mask,
  output logic                      mig_app_wdf_wren,
  output logic                      mig_app_wdf_end,
  input  logic                      mig_app_wdf_rdy,

  input  logic                      core_rst,
  input  logic                      core_bus_valid,
  input  logic                      core_bus_write,
  input  logic [15:0]               core_bus_address,
  input  logic [31:0]               core_bus_wdata,
  output logic [31:0]               core_bus_rdata,
  output logic                      core_bus_ready,
  output logic                      core_bus_error,
  input  logic                      core_sample_tick,
  output logic                      core_sample_valid,
  output synth_pkg::pcm_t           core_sample_l,
  output synth_pkg::pcm_t           core_sample_r,
  output logic                      core_busy,
  output logic                      core_ext_req_valid,
  input  logic                      core_ext_req_ready,
  output logic [31:0]               core_ext_req_addr,
  input  logic                      core_ext_rsp_valid,
  input  logic [LINE_WORDS*16-1:0]  core_ext_rsp_data,
  output logic                      core_mem_debug_hit_pulse,
  output logic                      core_mem_debug_miss_pulse,
  output logic                      core_mem_debug_response_pulse,
  output logic [15:0]               core_mem_debug_response_latency
);
  smart_artix_sd_native_asset_loader #(
    .LBA_WIDTH(LBA_WIDTH),
    .MIG_ADDR_WIDTH(MIG_ADDR_WIDTH),
    .MIG_DATA_WIDTH(MIG_DATA_WIDTH)
  ) loader (
    .clk,
    .rst,
    .start(loader_start),
    .ddr_init_calib_complete(loader_ddr_init_calib_complete),
    .busy(loader_busy),
    .asset_loaded(loader_asset_loaded),
    .sd_initialized(loader_sd_initialized),
    .status_state(loader_status_state),
    .sd_error_code(loader_sd_error_code),
    .loader_error_code(loader_error_code),
    .bytes_loaded(loader_bytes_loaded),
    .sf2_size_bytes(loader_sf2_size_bytes),
    .current_lba(loader_current_lba),
    .sd_cmd_valid,
    .sd_cmd_ready,
    .sd_cmd_index,
    .sd_cmd_arg,
    .sd_cmd_resp_type,
    .sd_cmd_data_read,
    .sd_cmd_block_len,
    .sd_cmd_block_count,
    .sd_rsp_valid,
    .sd_rsp_status,
    .sd_rsp_data,
    .sd_data_valid,
    .sd_data_ready,
    .sd_data,
    .sd_data_last,
    .sd_data_status,
    .mig_app_addr,
    .mig_app_cmd,
    .mig_app_en,
    .mig_app_rdy,
    .mig_app_wdf_data,
    .mig_app_wdf_mask,
    .mig_app_wdf_wren,
    .mig_app_wdf_end,
    .mig_app_wdf_rdy
  );

  wavetable_line_memory_core #(
    .LINE_WORDS(LINE_WORDS)
  ) core (
    .clk,
    .rst(core_rst),
    .bus_valid(core_bus_valid),
    .bus_write(core_bus_write),
    .bus_address(core_bus_address),
    .bus_wdata(core_bus_wdata),
    .bus_rdata(core_bus_rdata),
    .bus_ready(core_bus_ready),
    .bus_error(core_bus_error),
    .sample_tick(core_sample_tick),
    .sample_valid(core_sample_valid),
    .sample_l(core_sample_l),
    .sample_r(core_sample_r),
    .busy(core_busy),
    .ext_req_valid(core_ext_req_valid),
    .ext_req_ready(core_ext_req_ready),
    .ext_req_addr(core_ext_req_addr),
    .ext_rsp_valid(core_ext_rsp_valid),
    .ext_rsp_data(core_ext_rsp_data),
    .mem_debug_hit_pulse(core_mem_debug_hit_pulse),
    .mem_debug_miss_pulse(core_mem_debug_miss_pulse),
    .mem_debug_response_pulse(core_mem_debug_response_pulse),
    .mem_debug_response_latency(core_mem_debug_response_latency)
  );
endmodule
